AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Asset shipper
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/asset-sender-1.0-SNAPSHOT.jar
      Handler: com.paladincloud.assetsender.AssetDoneHandler
      Runtime: java21
      Description: Java function
      MemorySize: 2048
      Timeout: 120
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: --enable-preview
