spring:
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT cfkey, value from  pac_config_properties where application=? and profile=? and label=?
        native:
          search-locations: classpath:/shared
  datasource:
    url: jdbc:mysql://pacbot-data.ca1f8qf1livk.us-east-1.rds.amazonaws.com:3306/pacmandata?autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: pacbot
    password: "***REMOVED***"
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
  profiles:
    active: ${CONFIG_SOURCE:jdbc}          
  security:
    user:
      name: user
      password: pacman

server:  
  port: 8888
  servlet:
    context-path: /api/config

 
