FROM anapsix/alpine-java
MAINTAINER pacman-rule-execution-engine
RUN \
    mkdir -p /aws && \
    apk -Uuv add groff less python3 py3-pip && \
    pip3 install --upgrade pip && \
    pip3 install awscli && \
    apk --purge -v del py3-pip && \
    rm -rf /var/cache/apk/*

ADD fetch_and_run.sh ~/fetch_and_run.sh
RUN chmod 755 /~/fetch_and_run.sh
