AWSTemplateFormatVersion: "2010-09-09"
Resources:
  paladincloudAgentRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'tenant_ro'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::xxxxxxxx:role/tenant_ro
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/AWSSupportAccess
        - arn:aws:iam::aws:policy/AmazonGuardDutyReadOnlyAccess
        