FROM nginx:1.21.6

LABEL maintainer="NGINX Docker Maintainers <docker-maint@nginx.com>"

ARG HTML_FILE
ENV HTML_FILE=$HTML_FILE

# Install required packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        python3 \
        python3-distutils \
        unzip \
        gnupg \
    && rm -rf /var/lib/apt/lists/* \
    && curl -O https://bootstrap.pypa.io/pip/3.6/get-pip.py \
    && python3 get-pip.py \
    && pip install awscli

# Create the target directory
RUN mkdir -p /etc/nginx/html/

COPY nginx.conf /etc/nginx/nginx.conf
COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

EXPOSE 80