export const imagesToPreLoad = [
    'in-sla',
    'out-sla',
    'category-security',
    'category-operations',
    'category-cost',
    'category-tagging',
    'violations-low-icon',
    'violations-medium-icon',
    'violations-high-icon',
    'violations-critical-icon',
    'policy-icon',
    'autofix',
    'no-autofix',
];
