name: Sonarcloud-Build
on:
  push:
    branches:
      - master
      - v*
  pull_request:
    branches:
      - master
      - c*

jobs:
  sonarcloudBuild:
    name: SonarCloud-Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: running update
        run: sudo apt update

      - name: Install Maven
        run: |
          sudo apt install maven -y

      - name: Check for changed folders
        id: changed_folders
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Extract unique folder names from the list of changed files
          changed_folders=$(echo "$changed_files" | xargs -n1 dirname | sort -u)

          echo "Changed folders:"
          echo "$changed_folders"

          # Set an output variable with the list of changed folders
          echo "::set-output name=changed_folders::$changed_folders"

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          export MAVEN_OPTS="-Xmx3000m -XX:+UnlockDiagnosticVMOptions -XX:GCLockerRetryAllocationCount=100"
          export SONAR_SCANNER_OPTS="-Xmx3000m"

          # Use the list of changed folders to define actions based on the folder
          for folder in ${{ steps.changed_folders.outputs.changed_folders }}; do
            echo "Building folder: $folder"
            
            if [[ "$folder" == "webapp" ]]; then
              echo "Folder 'webapp' has changed. Perform action A."
              # Add your action for 'webapp' here
            elif [[ "$folder" == "jobs" ]]; then
              echo "Folder 'jobs' has changed. Perform action B."
              # Add your action for 'jobs' here
            elif [[ "$folder" == "api" ]]; then
              echo "Folder 'api' has changed. Perform action C."
              # Add your action for 'api' here
            elif [[ "$folder" == "common" ]]; then
              echo "Folder 'common' has changed. Perform action D."
              # Add your action for 'common' here
            else
              echo "Folder '$folder' has changed. No specific action defined."
            fi
          done
